### ISSUE TITLE
Crash with binnie-mods-2.0-pre2

### ISSUE THREAD

**Issue by aarondandy** [lawremi/PerFabricaAdAstra#33]
Various mods, including:

* binnie-mods-2.0-pre2
* CustomOreGen-1.7.10-1.2.17
* PFAA-1.7.10-0.2.23
* Forge 10.13.2.1235

This exception occurs after entering a single-player (presumably multi-player) world after upgrading to binnie-mods-2.0-pre2 .

Stacktrace:
```text
java.lang.IndexOutOfBoundsException: Index: 4, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.pfaa.geologica.block.GeoBlock.getGeoMaterial(GeoBlock.java:135)
	at org.pfaa.geologica.block.GeoBlock.getUnderlayIcon(GeoBlock.java:202)
	at org.pfaa.block.CompositeBlock.func_149673_e(CompositeBlock.java:65)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4800)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at org.pfaa.geologica.client.render.CompositeBlockRenderer.renderWorldBlockPass(CompositeBlockRenderer.java:47)
	at org.pfaa.geologica.client.render.CompositeBlockRenderer.renderWorldBlock(CompositeBlockRenderer.java:37)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.pfaa.geologica.block.GeoBlock.getGeoMaterial(GeoBlock.java:135)
	at org.pfaa.geologica.block.GeoBlock.getUnderlayIcon(GeoBlock.java:202)
	at org.pfaa.block.CompositeBlock.func_149673_e(CompositeBlock.java:65)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4800)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at org.pfaa.geologica.client.render.CompositeBlockRenderer.renderWorldBlockPass(CompositeBlockRenderer.java:47)
	at org.pfaa.geologica.client.render.CompositeBlockRenderer.renderWorldBlock(CompositeBlockRenderer.java:37)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
```

**Comment by lawremi** [comment]
I tried to reproduce this by creating a new world, but nothing broke. Is there something specific that you might be doing?

**Comment by aarondandy** [comment]
I can't reproduce this exact crash on my laptop either! Very strange as I version my multimc folder using git so I'm sure everything is identical. It does still crash at the same point but for different reasons related to NEI. I will try again later on my desktop when I have a chance and see if I can find some more information. I'm removing mods at the moment to see what causes it.

**Comment by aarondandy** [comment]
I don't get this error anymore with binnie-mods-2.0-pre3 (three) so I am closing. Now the error is related to NEI/RotaryCraft/BuildCraft/Binnie .
