### ISSUE TITLE
Crash with latest commit 8abf89e

### ISSUE THREAD

**Issue by middleeasternfag** [lawremi/PerFabricaAdAstra#62]
I compiled PFAA with the latest commit and it crashed on startup.
```
[Client thread/ERROR] [FML]: Caught exception from PFAAChemica
java.lang.ExceptionInInitializerError
	at org.pfaa.chemica.model.Compound$Compounds.<clinit>(Compound.java:78) ~[Compound$Compounds.class:?]
	at org.pfaa.chemica.ChemicaBlocks.<clinit>(ChemicaBlocks.java:24) ~[ChemicaBlocks.class:?]
	at org.pfaa.chemica.registration.BlockRegistration.init(BlockRegistration.java:14) ~[BlockRegistration.class:?]
	at org.pfaa.chemica.registration.CommonRegistrant.preregister(CommonRegistrant.java:10) ~[CommonRegistrant.class:?]
	at org.pfaa.chemica.Chemica.preload(Chemica.java:43) ~[Chemica.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at org.pfaa.chemica.model.Chemical.getSolubility(Chemical.java:18) ~[Chemical.class:?]
	at org.pfaa.chemica.model.Chemical.isSoluble(Chemical.java:27) ~[Chemical.class:?]
	at org.pfaa.chemica.model.SimpleChemical.inferAqueous(SimpleChemical.java:93) ~[SimpleChemical.class:?]
	at org.pfaa.chemica.model.SimpleChemical.<init>(SimpleChemical.java:44) ~[SimpleChemical.class:?]
	at org.pfaa.chemica.model.SimpleChemical.<init>(SimpleChemical.java:31) ~[SimpleChemical.class:?]
	at org.pfaa.chemica.model.Element.<init>(Element.java:609) ~[Element.class:?]
	at org.pfaa.chemica.model.Element.<init>(Element.java:617) ~[Element.class:?]
	at org.pfaa.chemica.model.Element.<init>(Element.java:625) ~[Element.class:?]
	at org.pfaa.chemica.model.Element.<init>(Element.java:631) ~[Element.class:?]
	at org.pfaa.chemica.model.Element.<init>(Element.java:636) ~[Element.class:?]
	at org.pfaa.chemica.model.Element.<init>(Element.java:640) ~[Element.class:?]
	at org.pfaa.chemica.model.Element.<clinit>(Element.java:32) ~[Element.class:?]
	... 49 more
```

**Comment by lawremi** [comment]
Thanks. The code is in the process of being ported and is not expected to work right now. Please continue to use the 1.7.10 branch.

**Comment by middleeasternfag** [comment]
No problem. I'm just glad you're still maintaining it since I've read pfaa.org years ago and have ever since been watching this project.
